trigger:
- master

pool:
  name: Myagent

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
    - job: Build
      displayName: 'Build Application'
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '16.x'
          displayName: 'Install Node.js'

        - script: npm install
          displayName: 'Install Dependencies'

        - script: ng build
          displayName: 'Build stage'

        - task: PublishPipelineArtifact@1
          inputs:
            artifactName: 'angular-app'
            targetPath: 'dist/employee_management'
          displayName: 'Publish Artifacts'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
    - job: Test

      displayName: 'Run Tests'
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '16.x'
        - script: npm install
          displayName: 'Install Dependencies'
        - script: choco install firefox -y
          displayName: 'Install firefox to run test'


        - script: ng test --watch=false --browsers=ChromeHeadless
          displayName: 'stage test'   



#- stage: deploy 
#    displayName: 'deploy Stage'
#    dependsOn: Test    #publish only when test succeed
#    jobs:
#      - job: Publish
#        displayName: 'Publish Artifact to Azure Artifacts'
#        steps:
#          - task: UniversalPackages@0 //task used to publish artifact 
#            displayName: 'Publish Artifact'
#            inputs:
#              command: 'publish'
#              publishDirectory: '$(Build.ArtifactStagingDirectory)'
#              vstsFeedPublish: nameof artifact
#              vstsFeedPackagePublish: 

#          - task: AzureWebApp@1
#          displayName: 'Deploy to Azure App Service'
#          inputs:
#            azureSubscription: '<Your_Azure_Subscription>'
#            appName: '<Your_App_Service_Name>'
#            package: '$(Build.ArtifactStagingDirectory)/<Your_Package_Name>.zip'
#            deployType: 'zipDeploy'