trigger:
- master

pool:
  name: Myagent

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
    - job: Build
      displayName: 'Build Application'
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '16.x'
          displayName: 'Install Node.js'

        - script: npm install
          displayName: 'Install Dependencies'

        - script: npm run build
          displayName: 'Build stage'

        - task: PublishPipelineArtifact@1
          inputs:
            artifactName: 'angular-app'
            targetPath: 'dist/employee_management'
          displayName: 'Publish Artifacts'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
    - job: Test
      displayName: 'Run Tests'
      steps:
        - script: npm install
          displayName: 'Install Dependencies'

        - script: ng test
          displayName: 'stage test'     